version: '3.8'

services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    container_name: rancher
    ports:
      - 8182:443
    networks:
      - services
    volumes:
    - rancher-data:/var/lib/rancher
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Lisbon"
    #command: --no-cacerts
    privileged: true

networks:
  services:
    external: true

volumes:
  rancher-data:
