services:
  lldap:
    image: lldap/lldap:latest
    restart: unless-stopped
    container_name: LLDAP
    ports:
      - 3890:3890 # For LDAP, not recommended to expose, see Usage section.
#      - 6360:6360 # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      - 17170:17170 # For the web front-end
    networks:
      - <NETWORK>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ldap_data:/data
    environment:
      MGID: "${GID-1000}"
      TZ: "Europe/Lisbon"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.entrypoints=http"
      - "traefik.http.routers.lldap.rule=Host(`URL`)"
      - "traefik.http.middlewares.lldap-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lldap.middlewares=lldap-https-redirect"
      - "traefik.http.routers.lldap-secure.entrypoints=https"
      - "traefik.http.routers.lldap-secure.rule=Host(`URL`)"
      - "traefik.http.routers.lldap-secure.tls=true"
      - "traefik.http.routers.lldap-secure.service=lldap"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"
      - "traefik.docker.network=NETWORK"

networks:
  NETWORK:
    external: true

volumes:
  ## LOCAL VOLUMES
  #ldap_data:
  ## NFS VOLUMES
  ldap_data:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=<IP>,rw"
      device: ":/PATH/"
