version: '3.3'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:<VERSION/LATEST>
    container_name: transmission
    restart: unless-stopped
    ports:
      - 8180:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - <NETWORK>
    volumes:
      - /path/config:/config
      - /path/downloads:/downloads
      - /path/watch:/watch
    env_file:
      - .env # <FILE MUST BE CREATED apply chmod 600 .env>
    environment:
      - PUID=<run id command to get PUID and PGID>
      - PGID=<run id command to get PUID and PGID>
      # - TZ=Europe/Lisbon <OPTIONAL>
      #- TRANSMISSION_WEB_HOME= #optional
      - USER=${.env_key}
      - PASS=${.env_key}
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional

networks:
  NETWORK:
    external: true
