version: '3.3'

services:
  crowdsec:
    image: crowdsecurity/crowdsec:<VERSION/LATEST>
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - <NETWORK>
    environment:
      PUID: <run id command to get PUID and PGID>
      PGID: <run id command to get PUID and PGID>
      # TZ: Europe/Lisbon <OPTIONAL>
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - /path/config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik_traefik-logs:/var/log/traefik/:ro
  # bouncer-traefik:
  #   image: fbonalair/traefik-crowdsec-bouncer:<VERSION/LATEST>
  #   container_name: crowdsec_bouncer
  #   restart: unless-stopped
  #   networks:
  #     - <NETWORK>
  #   env_file:
  #     - .env # <FILE MUST BE CREATED apply chmod 600 .env>
  #   environment:
  #     PUID: <run id command to get PUID and PGID>
  #     PGID: <run id command to get PUID and PGID>
  #     # TZ: Europe/Lisbon #optional
  #     CROWDSEC_BOUNCER_API_KEY: ${.env_key}
  #     CROWDSEC_AGENT_HOST: crowdsec:8080
  #   depends_on:
  #     - crowdsec

networks:
  NETWORK:
    external: true

volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_traefik-logs:
    external: true
