version: '3.8'
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    container_name: notify
    ports:
      - 80:80
    networks:
      - services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    command:
      - serve
networks:
  services:
    external: true