version: '3.3'

services:
  adguard:
    image: adguard/adguardhome:<VERSION/LATEST>
    container_name: adguard
    restart: unless-stopped
    ports:
      # UNCOMMENT IF NEEDED....
      - 53:53/tcp
      - 53:53/udp
      #- 67:67/udp
      #- 68:68/udp
      #- 80:80/tcp
      #- 443:443/tcp
      #- 443:443/udp
      - 3000:3000/tcp
      #- 853:853/tcp
      #- 784:784/udp
      #- 853:853/udp
      #- 8853:8853/udp
      #- 5443:5443/tcp
      #- 5443:5443/udp
    networks:
      - <NETWORK>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /PATH/conf:/opt/adguardhome/conf
      - /PATH/work:/opt/adguardhome/work
    environment:
      - PUID=<run id command to get PUID and PGID>
      - PGID=<run id command to get PUID and PGID>
      # - TZ=Europe/Lisbon #optional
      # - CONFIGFILE=/PATH/conf/adguardhome-sync.yaml #optional
    # ALL THIS LABELS ARE USED ASSUMING THAT YOU ARE USING TRAEFIK AS A REVERSE PROXY
    # OTHERWISE COMMENT ALL LABEL LINES
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`URL`)"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.routers.adguard-secure.entrypoints=https"
      - "traefik.http.routers.adguard-secure.rule=Host(`URL`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.docker.network=NETWORK"
networks:
  NETWORK:
    external: true