version: '3.3'

services:
  watchtower:
    image: containrrr/watchtower:<VERSION/LATEST>
    container_name: watchtower
    restart: unless-stopped
    networks:
      - <NETWORK>
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCHEDULE: "0 0 1 * * *" # Every Day an 1am
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"

networks:
  NETWORK:
    external: true

# ONLY IMAGES WITH THE TAG LATEST WILL BE UPDATED