ENV['VAGRANT_NO_PARALLEL'] = 'yes'

BOX         = 'ubuntu/focal64'
BOX_VERSION = '20230207.0.0'
CPUS        = 2
MEMORY	    = 2048
STATIC_IP   = '166.10.10.2'

Vagrant.configure("2") do |config|
  config.vm.box               = BOX
  config.vm.box_version       = BOX_VERSION
  config.vm.disk :disk, name: BOX, size: '20GB'

  config.vm.box_check_update  = false
  config.vm.hostname          = 'nyxcloud.net'

  config.vm.network 'public_network', bridge: 'eno1', ip: STATIC_IP

  config.vm.provider 'virtualbox' do |v|
    v.name    = 'pihole'
    v.memory  = MEMORY
    v.cpus    = CPUS
  end
end