version: '3.9'
services:
  passbolt_mariaDB:
    image: mariadb:10.3
    restart: always
    container_name: passbolt_mariaDB
    ports:
      - 3306:3306
    networks:
      - services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - database_volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  passbolt:
    image: passbolt/passbolt:latest-ce
    restart: always
    container_name: passbolt
    ports:
      - 8181:80
    depends_on:
      - passbolt_mariaDB
    networks:
      - services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Lisbon"
      APP_FULL_BASE_URL: https://passbolt.nyxcloud.net
      DATASOURCES_DEFAULT_HOST: "passbolt_mariaDB"
      DATASOURCES_DEFAULT_USERNAME: ${MYSQL_USER}
      DATASOURCES_DEFAULT_PASSWORD: ${MYSQL_PASSWORD}
      DATASOURCES_DEFAULT_DATABASE: ${MYSQL_DATABASE}
    command: ["/usr/bin/wait-for.sh", "-t", "0", "passbolt_mariaDB:3306", "--", "/docker-entrypoint.sh"]

networks:
  services:
    external: true

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

# docker-compose -f docker-compose.yaml exec passbolt su -m -c "/usr/share/php/passbolt/bin/cake passbolt register_user -u hilario.nuno@hotmail.com -f Nuno -l Hilario -r admin" -s /bin/sh www-data
