version: '3.3'
services:
  adguard:
    image: adguard/adguardhome:latest
    #ports:
      #- 53:53/tcp
      #- 53:53/udp
      #- 67:67/udp
      #- 68:68/udp
      #- 80:80/tcp
      #- 443:443/tcp
      #- 443:443/udp
      #- 3000:3000/tcp
      #- 853:853/tcp
      #- 784:784/udp
      #- 853:853/udp
      #- 8853:8853/udp
      #- 5443:5443/tcp
      #- 5443:5443/udp
    networks:
      - services-dhcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/padawan/adguard/conf:/opt/adguardhome/conf
      - /home/padawan/adguard/work:/opt/adguardhome/work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      # - CONFIGFILE=/home/padawan/adguard/conf/adguardhome-sync.yaml #optional
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`adguard.nyxcloud.net`)"
      #- "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      #- "traefik.http.routers.adguard-secure.entrypoints=https"
      #- "traefik.http.routers.adguard-secure.rule=Host(`adguard.nyxcloud.net`)"
      #- "traefik.http.routers.adguard-secure.tls=true"
      #- "traefik.http.routers.adguard-secure.service=adguard"
      #- "traefik.http.services.adguard.loadbalancer.server.port=3000"
      #- "traefik.docker.network=services-dhcp"
networks:
  services-dhcp:
    external: true

# docker stack deploy --compose-file docker-compose.yml nyxcloud
