apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/Data/PVC/wordpress
    server: 10.0.90.6