version: '3.8'
services:
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: tunnel
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${tunnel_token}
