version: '3.3'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:<VERSION/LATEST>
    container_name: vscode
    restart: unless-stopped
    ports:
      - 8443:8443
    networks:
      - <NETWORK>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/config:/config
    env_file:
      - .env # <FILE MUST BE CREATED apply chmod 600 .env>
    environment:
      - PUID=<run id command to get PUID and PGID>
      - PGID=<run id command to get PUID and PGID>
      # - TZ=Europe/Lisbon <OPTIONAL>
      - PASSWORD=${.env_key}
      - SUDO_PASSWORD=${.env_key}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.entrypoints=http"
      - "traefik.http.routers.code-server.rule=Host(`URL`)"
      - "traefik.http.middlewares.code-server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.code-server.middlewares=code-server-https-redirect"
      - "traefik.http.routers.code-server-secure.entrypoints=https"
      - "traefik.http.routers.code-server-secure.rule=Host(`URL`)"
      - "traefik.http.routers.code-server-secure.tls=true"
      - "traefik.http.routers.code-server-secure.service=code-server"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
      - "traefik.docker.network=NETWORK"

networks:
  NETWORK:
    external: true