version: '3.3'

services:
  kuma:
    image: louislam/uptime-kuma:<VERSION/LATEST>
    container_name: kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - <NETWORK>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/data:/app/data
    environment:
      - PUID=<run id command to get PUID and PGID>
      - PGID=<run id command to get PUID and PGID>
      # - TZ=Europe/Lisbon <OPTIONAL>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.entrypoints=http"
      - "traefik.http.routers.kuma.rule=Host(`URL`)"
      - "traefik.http.middlewares.kuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kuma.middlewares=kuma-https-redirect"
      - "traefik.http.routers.kuma-secure.entrypoints=https"
      - "traefik.http.routers.kuma-secure.rule=Host(`URL`)"
      - "traefik.http.routers.kuma-secure.tls=true"
      - "traefik.http.routers.kuma-secure.service=kuma"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=NETWORK"

networks:
  NETWORK:
    external: true