version: '3.9'

services:
#  mysql:
#    image: mysql:latest
#    restart: unless-stopped
#    container_name: mysql
#    volumes:
#      - semaphore-mysql:/var/lib/mysql
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_DATABASE=semaphore
#      - MYSQL_USER=semaphore
#      - MYSQL_PASSWORD=secret-password  # change!
  semaphore:
    image: semaphoreui/semaphore:v2.8.90
    restart: unless-stopped
    container_name: ansible
    ports:
      - 3000:3000
    networks:
      - services
    volumes:
      - ansible-inventory:/inventory:ro
      - ansible-authorized-keys:/authorized-keys:ro
      - ansible-config:/etc/semaphore:rw
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - SEMAPHORE_DB_USER=${SEMAPHORE_DB_USER}
      - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS}
      - SEMAPHORE_DB_HOST=${SEMAPHORE_DB_HOST}
      - SEMAPHORE_DB_PORT=${SEMAPHORE_DB_PORT}
      - SEMAPHORE_DB_DIALECT=${SEMAPHORE_DB_DIALECT}
      - SEMAPHORE_DB=${SEMAPHORE_DB}
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=AMIxYI0ukSSSODUYgnJce1zetqaCacZ0R0zaRgKWxtg=
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
#    depends_on:
#      - mysql
volumes:
  ansible-inventory:
    driver: local
  ansible-authorized-keys:
    driver: local
  ansible-config:
    driver: local
networks:
  services:
    external: true
