version: '3.3'

services:
  bind9:
    image: ubuntu/bind9:<VERSION/LATEST>
    container_name: bind9
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - <NETWORK>
    volumes:
      - /path/cache:/var/cache/bind:rw
      - /path/config:/etc/bind:ro
      - /path/records:/var/lib/bind:rw
    environment:
      - PUID=<run id command to get PUID and PGID>
      - PGID=<run id command to get PUID and PGID>
      # - TZ=Europe/Lisbon <OPTIONAL>
      - BIND9_USER=root

networks:
  NETWORK:
    external: true

