apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  namespace: bind9
  labels:
    app: bind9
  annotations:
    metallb.universe.tf/loadBalancerIPs: <METALLB RANGE IP>
spec:
  selector:
    app: bind9
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
    name: bind9-dns-tcp
  - protocol: UDP
    port: 53
    targetPort: 53
    name: bind9-dns-udp
  type: LoadBalancer