version: '3.3'
services:
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    networks:
      - services
    volumes:
      - /home/padawan/redis/data:/bitnami/redis/data
      #- /home/padawan/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
networks:
  services:
    external: true
